[17.0][MIG] delivery_line_sale_line_position: Migration to 17.0
xaviedoanhduy/stock-logistics-reporting pull request #2
Opened 2024-04-19 04:35 UTC by xaviedoanhduy

[Delivery Slip - Oscar Morgan - WH_IN_00006.pdf](https://github.com/xaviedoanhduy/stock-logistics-reporting/files/15033133/Delivery.Slip.-.Oscar.Morgan.-.WH_IN_00006.pdf)

2024-04-19 09:04 UTC, nguyenminhchien requested changes
The position does not show when Picking is Done
![image](https://github.com/xaviedoanhduy/stock-logistics-reporting/assets/8724793/266a3fb5-9e2f-45aa-b5c6-4a15013b1458)

2024-04-19 09:06 UTC, nguyenminhchien commented
this module depends on sale_order_line_position, so you can push a commit like this
https://github.com/nguyenminhchien/intrastat-extrastat/pull/4/commits/a7d489fb4e43e3a3e5daedef5ff867fedf38b9ed

2024-04-19 11:56 UTC, xaviedoanhduy commented
Thanks for your instructions, here is the new commit to add
test-requirements.txt.
<https://github.com/xaviedoanhduy/stock-logistics-reporting/pull/2/commits/f35182d68d4a2af0e8e95c1b8a7223c3b9c107c0>
If there is any problem, please reply to me in this email.

On Fri, Apr 19, 2024 at 4:06 PM Chien Nguyen ***@***.***>
wrote:

> this module depends on sale_order_line_position, so you can push a commit
> like this
> ***@***.***
> <https://github.com/nguyenminhchien/intrastat-extrastat/commit/a7d489fb4e43e3a3e5daedef5ff867fedf38b9ed>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/xaviedoanhduy/stock-logistics-reporting/pull/2#issuecomment-2066151142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVR5MVZUAI4VQSTBF5JFYSDY6DNCVAVCNFSM6AAAAABGOO53YWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANRWGE2TCMJUGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 

*Duy Do*

*Technical Consultant*

Trobz - The Art of Odoo

No.13, Street 7C1, An Phu Ward, Thu Duc City, HCMC, Vietnam

Mobile: +84 (0) 961618528 / Office: +84 (0) 961618528

***@***.*** / trobz.com / Skype: Do Anh Duy

2024-04-23 11:03 UTC, xaviedoanhduy commented
> The position does not show when Picking is Done ![image](https://private-user-images.githubusercontent.com/8724793/323899020-266a3fb5-9e2f-45aa-b5c6-4a15013b1458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjkzMjcsIm5iZiI6MTcxMzg2OTAyNywicGF0aCI6Ii84NzI0NzkzLzMyMzg5OTAyMC0yNjZhM2ZiNS05ZTJmLTQ1YWEtYjVjNi00YTE1MDEzYjE0NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTA0MzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWUzOTdjMjRhMmUwYzZjN2FkOTAxMzQ5Y2NhMGYwZmZlZWFlYTVmMDliMDk3NGRiOTMwY2E4ODc5MDRiNDA0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9hIeexf8jNszBQpi_spQhK6fwtINw-Z3hMA-1yp3XQQ)

I checked and there is no problem exporting that report, position not appearing because configuration group and permissions are missing, to display position when Picking is Done. You have to add group "Display Serial & Lot Number in Delivery Slips" to your user, then the product lines in the Operations tab of Picking must exist in the "Lots/Serial Numbers" view with the following menu path "Inventory/Products/Lots/Serial Numbers".

2024-04-24 03:00 UTC, nguyenminhchien requested changes
The checks are red.

2024-04-24 03:03 UTC, nguyenminhchien commented on test-requirements.txt
> +odoo-addon-sale_order_line_position @ git+https://github.com/OCA/sale-reporting.git@refs/pull/261/head#subdirectory=sale_order_line_position
the pull id is [264](https://github.com/OCA/sale-reporting/pull/264)

2024-04-24 03:16 UTC, nguyenminhchien approved these changes

2024-05-16 02:56 UTC, closed without merging